# 로컬 개발 환경 설정 (Git 추적 제외됨)
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/radotrip?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: devuser
    # 암호화된 비밀번호 (Jasypt 로 암호화). 실제 비밀번호는 ENC(...) 로 교체합니다.
    # password: ENC(Cf1DPF3tG1Z3ZxGZV+JHcA==)
    # 환경변수 TOUR_API_SERVICE_KEY가 정의되어 있으면 이를 사용하고, 없으면 발급받으신 아래 인증키를 기본값으로 사용합니다.
    password: 1234 
tourApi:  
  serviceKey: ${TOUR_API_SERVICE_KEY:UZ6G%2BkhrQvlmqNqkUDDanxsHhip1ZqJHGRx%2FEv76zzEDhI6NjSqxrKs3sIRN5go%2BvI8y2KPEkwaRey%2BghfkMUQ%3D%3D}
